apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.service.type}}
  selector:
    app: techtrends
    tag: latest
  ports:
  - port: {{ .Values.service.port}}
    targetPort: {{ .Values.service.targetPort}}
    protocol: {{ .Values.service.protocol}}